name: local_dense_biogpt
csv_file: D:\Bachelor_project\local\All_AP_pic_w_urls_50000.csv"
save_path: D:\Bachelor_project\runs
encoder: densenet
decoder: biogpt
training_phases: classification_then_text
epochs_classification: 5
epochs_text_generation: 5
batch_size: 8
learning_rate: 3e-5
num_datapoints: 5000
repetition_penalty: 1.3
top_k: 40
top_p: 0.9
