batch_size: 2
config: null
csv_file: local\Final_AP_Missing_Removed_12519.csv
decoder: scratch_decoder
encoder: scratch_encoder
epochs_classification: 1
epochs_text_generation: 1
freeze_encoder: false
img_size: 224
learning_rate: 3.0e-05
max_length: 128
name: local_resnet_gpt2_test
num_datapoints: 10000
repetition_penalty: 1.2
save_path: bachelor_runs
setup: local
top_k: 50
top_p: 0.95
training_phases: classification_only
