# configs/default.yaml

train:
  batch_size: 16
  epochs: 8
  lr: 0.0002

data:
  csv_path: data/subset_pneumonia_30.csv
  img_dir: data/JPG_AP
  reports_dir: data/Reports

run:
  out_dir: runs/${now:%Y-%m-%d_%H-%M}
  save_model: true
  max_length: 128
